### ISSUE TITLE
C++ standard used for compilation, and other compilation options

### ISSUE THREAD

**Issue by ninadhuilgol** [DS221-2021/Assignment2#2]
I would like to use C++17 features like `std::optional` in my program, but the makefiles don't specify which C++ standard is used for compilation. This default is different depending on the version of gcc used, so I can't tell for certain which language and library features can be used in my program. So can this option please be specified in the makefiles?
Also, if there are any other relevant compilation options to set that I am not aware of, I think they should be specified as well.

**Comment by cjain7** [comment]
This should be now addressed. Check the latest README file.

**Comment by ninadhuilgol** [comment]
Ok, thanks
