### ISSUE TITLE
OSX diff util does not have -Z flag(ignore trailing whitespace)

### ISSUE THREAD

**Issue by gprakhar6** [DS221-2021/Assignment2#3]
Maybe,
Consider using something like

```
d1=$(diff <(sed 's/[[:space:]]*$//g' ../tests/t3/q1o3.txt) out3.txt -qB)
```

Setup:
OSX (Big Sur)
Darwin Kernel Version 20.6.0

**Comment by cjain7** [comment]
@gprakhar6 
We will do compilation/testing on a linux operating system. If you don't have linux OS available, you can use replit IDE.

I'd assume there are very few students using OSX, hence we prefer to not ignore OSX compatibility.

**Comment by chandrashekar-cds** [comment]
We will be testing the code on Linux OS.. Hence the code you have developed using OSX must be made compatible to Linux OS before submission.( makefile )
