### ISSUE TITLE
Time measurement units

### ISSUE THREAD

**Issue by ninadhuilgol** [DS221-2021/Assignment2#4]
In Q2a, the README states that we should measure the time in milliseconds, while the code outline states we should measure in nanoseconds. Can you please clarify what units we should use?
Based on my observations, millisecond precision is insufficient, especially for small input sizes. For example, test 1 on my laptop runs in under 1ms for both tree search strategies, so the reported time becomes `0`. Moreover, binary search takes less than 1ms for all three test cases and so it always reports `0`

**Comment by cjain7** [comment]
The test cases are just for sanity checks. 
We recommend that you use large enough inputs to test your algorithm, or else you not be able to observe the behaviour of your algorithm properly.

(cc @chandrashekar-cds)
